# Klent Paraiso BSCS-3 
# 3rd Quarter Exam : Solving Systems of Equations Using Matrix Inverse 

# Part 1: Theory

In [5]:
import numpy as np

# Step 1: Define the matrix A (5x5) and vector B (5x1)
A = np.array([[3, 2, -1, 0, 0],
              [2, -1, 3, 0, 0],
              [1, 2, 4, 3, 0],
              [0, 1, -2, 2, 1],
              [0, 0, 3, 1, 4]])

B = np.array([1, 2, 3, 4, 5])

# Step 2: Calculate the inverse of matrix A
A_inv = np.linalg.inv(A)

# Step 3: Calculate the solution vector X
X = np.dot(A_inv, B)

# Step 4: Display the solution
print("The solution vector X is:")
print(X)


The solution vector X is:
[ 0.9057971  -0.99275362 -0.26811594  1.7173913   1.02173913]


# Part 2: Application to Real-World Computer Science Problem

In [10]:

# Step 1: Define the coefficient matrix A (5x5) and the constant vector B (5x1)
A = np.array([[3, 2, 1, 1, 0],
              [1, 4, 2, 0, 1],
              [2, 3, 4, 1, 0],
              [1, 1, 3, 5, 0],
              [0, 1, 2, 4, 3]])

B = np.array([100, 150, 120, 110, 140])

# Step 2: Calculate the inverse of matrix A
A_inv = np.linalg.inv(A)

# Step 3: Calculate the solution vector X (the data flows between servers)
X = np.dot(A_inv, B)

# Step 4: Display the solution
print("The data flow between the servers (x1, x2, x3, x4, x5) is:")
print(X)


The data flow between the servers (x1, x2, x3, x4, x5) is:
[ 7.36462094 32.23826715 -1.62454874 15.05415162 16.93140794]


# Part 3: Step-by-Stel Instructions

In [15]:


# Step 1: Define the coefficient matrix A (5x5 matrix)
A = np.array([
    [3, 2, 1, 1, 0],
    [1, 4, 2, 0, 1],
    [2, 3, 4, 1, 0],
    [1, 1, 3, 5, 0],
    [0, 1, 2, 4, 3]
])

# Step 2: Define the constant matrix B (5x1 matrix)
B = np.array([100, 150, 120, 110, 140])

# Step 3: Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    # Step 4: Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    # Step 5: Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    # Step 6: Display the solution (unknowns)
    print("Solution (Unknowns):")
    print(X)


Determinant of A: 277.0000000000002
Solution (Unknowns):
[ 7.36462094 32.23826715 -1.62454874 15.05415162 16.93140794]


# Part 4: Practice Problems
# Problem 1

In [20]:

# Define the coefficient matrix A (3x3 matrix)
A = np.array([
    [2, 1, -1],
    [-1, 3, 2],
    [1, -2, 4]
])

# Define the constant matrix B (3x1 matrix)
B = np.array([5, 6, 7])

# Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    # Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    # Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    # Display the solution (unknowns)
    print("Solution (Unknowns):")
    print(X)


Determinant of A: 38.99999999999999
Solution (Unknowns):
[2.64102564 1.61538462 1.8974359 ]


# Problem 2

In [22]:


# Define the coefficient matrix A (5x5 matrix)
A = np.array([
    [5, 3, 1, 1, 0],
    [4, 6, 2, 0, 1],
    [2, 7, 3, 1, 0],
    [1, 2, 4, 5, 0],
    [3, 4, 5, 0, 6]
])

# Define the constant matrix B (5x1 matrix)
B = np.array([200, 300, 150, 120, 250])

# Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    # Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    # Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    # Display the solution (unknowns)
    print("Solution (Unknowns):")
    print(X)


Determinant of A: 225.0
Solution (Unknowns):
[ -23.86666667  137.6        -336.          242.53333333  241.86666667]


# Problem 3

In [32]:
import numpy as np

# Step 1: Define the coefficient matrix A (7x7 matrix) with actual values
A = np.array([
    [2, 3, 1, 4, 5, 1, 2],
    [4, 6, 2, 1, 3, 7, 3],
    [1, 2, 3, 4, 2, 6, 1],
    [5, 3, 2, 1, 4, 6, 5],
    [3, 2, 1, 5, 3, 4, 2],
    [4, 5, 6, 3, 1, 2, 1],
    [1, 2, 1, 4, 2, 3, 5]
])

# Step 2: Define the constant matrix B (7x1 matrix) with actual values
B = np.array([10, 20, 15, 30, 25, 35, 40])

# Step 3: Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    # Step 4: Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    # Step 5: Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    # Step 6: Display the solution (unknowns)
    print("Solution (Unknowns):")
    print(X)


Determinant of A: -39825.999999999956
Solution (Unknowns):
[ 3.20883343  0.46778486  1.45093657  3.88979561 -5.36345603 -0.78591875
  6.38602923]


# Problem 4

In [35]:

# Step 1: Define the coefficient matrix A (5x5 matrix) with the actual values
A = np.array([
    [2, 3, 1, 4, 5],
    [1, 2, 3, 4, 2],
    [3, 4, 5, 6, 7],
    [4, 5, 6, 7, 8],
    [2, 4, 1, 3, 5]
])

# Step 2: Define the constant matrix B (5x1 matrix) with the actual values
B = np.array([100, 200, 300, 400, 500])

# Step 3: Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    # Step 4: Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    # Step 5: Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    # Step 6: Display the solution (unknowns)
    print("Solution (Unknowns):")
    print(X)


Determinant of A: -30.000000000000004
Solution (Unknowns):
[-133.33333333  293.33333333   80.         -106.66666667  -33.33333333]


# Problem 5

In [38]:
def solve_network_routing(A, B):
    """
    Solves the system of linear equations A * X = B using matrix inversion.

    Parameters:
    A (numpy.ndarray): The coefficient matrix (n x n).
    B (numpy.ndarray): The constant matrix (n x 1).

    Returns:
    numpy.ndarray: The solution vector X (n x 1).
    """
    # Step 1: Check if the matrix A is invertible (determinant should not be zero)
    det_A = np.linalg.det(A)
    if det_A == 0:
        print("Matrix A is singular and cannot be inverted!")
        return None
    
    # Step 2: Calculate the inverse of matrix A
    A_inv = np.linalg.inv(A)
    
    # Step 3: Solve for X using the matrix inverse method (X = A^-1 * B)
    X = np.dot(A_inv, B)
    
    # Step 4: Return the solution (unknowns)
    return X

# Example usage:
if __name__ == "__main__":
    # Coefficient matrix A (5x5 matrix)
    A = np.array([
        [3, 2, 1, 1, 0],
        [1, 4, 2, 0, 1],
        [2, 3, 4, 1, 0],
        [1, 1, 3, 5, 0],
        [0, 1, 2, 4, 3]
    ])
    
    # Constant matrix B (5x1 matrix)
    B = np.array([100, 150, 120, 110, 140])

    # Solve the system of equations
    solution = solve_network_routing(A, B)
    
    # If the solution is valid, print the results
    if solution is not None:
        print("Solution (Unknowns):")
        print(solution)


Solution (Unknowns):
[ 7.36462094 32.23826715 -1.62454874 15.05415162 16.93140794]
